### ISSUE TITLE
Non-US keyboard layouts

### ISSUE THREAD

**Issue by moridius** [meh/rust-uinput#11]
I'm using a german keyboard layout. If I do
`device.click("&keyboard::Key::Minus).unwrap();`
I get a "ß" which is the sign on the key where the minus key would be on a US keyboard.

What's the plan for non-US keyboard layouts? Is there no way to use them with this lib or am I missing something?

**Comment by mariuszbie** [comment]
This library is for emulating input like you would type on your actual keyboard, so to change keyboard layout you'll have to use something else.

**Comment by moridius** [comment]
Thanks for your reply. My problem was, that the library did **not** behave like I would type on my actual keyboard. If I press the minus key on my keyboard I get a minus character, not a ß.

However, this issue is old and does not concern me anymore. Closing.
